# Generated by Django 5.1.7 on 2025-03-10 21:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(default='-', max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
