# Generated by Django 5.1.7 on 2025-03-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensecategory_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
