# Generated by Django 5.1.7 on 2025-03-13 13:44

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_amount_currency_alter_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=63, unique=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Expense tag',
                'verbose_name_plural': 'Expense tags',
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', '€')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='budget_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', '€')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='expenses.expensetag'),
        ),
    ]
